# run: conda env create --file environment.yml
name: py10
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - cachetools
  - av<9
  - cython
  - ezc3d
  - ffmpeg
  - imageio
  - matplotlib
  - mkl
  - trimesh
  - numba
  - numpy<2.0
  - libiconv
  - pandas
  - Pillow
  - scikit-image
  - scikit-learn
  - scikit-sparse
  - tqdm
  - conda-forge::mayavi>=4.8
  - conda-forge::PySide6==6.7.1
  - conda-forge::ffmpeg-python
  - pip:
    - distutils
    - addict
    - tensorflow==2.15
    - tensorflow-hub
    - chumpy
    - embreex
    - einops
    - imageio-ffmpeg
    - importlib_resources
    - jpeg4py
    - more_itertools
    - opencv-python
    - pyrender
    - tetgen
    - pymeshfix
    - -e $CODE_DIR/fleras
    - -e $CODE_DIR/affine_combining_autoencoder
    - -e $CODE_DIR/cameralib
    - -e $CODE_DIR/boxlib
    - -e $CODE_DIR/poseviz
    - -e $CODE_DIR/smplfitter
    - -e $CODE_DIR/simplepyutils
    - -e $CODE_DIR/rlemasklib
    - -e $CODE_DIR/barecat3
    - -e $CODE_DIR/tensorflow-inputs
    - -e $CODE_DIR/posepile
    - -e $CODE_DIR/blendipose
    - -e $CODE_DIR/blendify
    - -e $CODE_DIR/nlf-pipeline
#    - git+https://github.com/isarandi/fleras.git
#    - git+https://github.com/isarandi/cameralib.git
#    - git+https://github.com/isarandi/boxlib.git
#    - git+https://github.com/isarandi/poseviz.git
#    - git+https://github.com/isarandi/smplfitter.git
#    - git+https://github.com/isarandi/simplepyutils.git
#    - git+https://github.com/isarandi/tf-parallel-map.git
#    - git+https://github.com/isarandi/BareCat.git
#    - git+https://github.com/isarandi/rlemasklib.git
#    - git+https://github.com/isarandi/tensorflow-inputs.git
